# Generated by Django 3.0.5 on 2020-04-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='up',
            field=models.BooleanField(default=False),
        ),
    ]
